action/action/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('account.urls')),
    path('', include('items.urls')),
]

action/core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    #path('<uuid:pk>/', views.view_all, name='view_all'),
]

action/items/urls.py
from django.urls import path
from . import views

app_name = 'items'

urlpatterns = [
    path('items/', views.items, name='items'),
    path('add/', views.add_item, name='add'),
    path('<uuid:pk>/', views.view_items, name='view'),
    path('<uuid:pk>/edit/', views.edit_items, name='edit'),
    path('<uuid:pk>/delete/', views.delete_items, name='delete'),
] 

action/items/models.py
from django.db import models

import uuid

from account.models import User

class Items(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    fleet = models.CharField(max_length=255)
    tail = models.CharField(max_length=255)
    remark = models.TextField(blank=True, null=True)
    required_action = models.TextField(blank=True, null=True)
    owner = models.CharField(max_length=255)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    logged = models.CharField(max_length=255)
    duedate = models.CharField(max_length=255)
    contact = models.CharField(max_length=255)
    level1 = models.CharField(max_length=255)
    level2 = models.CharField(max_length=255)
    level3 = models.CharField(max_length=255)
    status = models.CharField(max_length=255)
    requestedby = models.CharField(max_length=255)
    

    def __str__(self):
        self.name

action/items/views.py
from django.shortcuts import render, redirect
from .models import Items
from django.contrib.auth.decorators import login_required

@login_required
def items(request):
    items = Items.objects.filter(created_by=request.user)

    return render(request, 'items/items.html',{
        'items':items
    })

@login_required
def view_items(request, pk):
    items = Items.objects.filter(created_by=request.user).get(pk=pk)

    return render(request, 'items/viewitem.html',{
        'items':items
    })


@login_required
def add_item(request):
    if request.method == "POST":
        fleet = request.POST.get('fleet', '')
        tail = request.POST.get('tail', '')
        remark = request.POST.get('remark', '')
        required_action = request.POST.get('required_action', '')
        logged = request.POST.get('logged', '')
        duedate = request.POST.get('duedate', '')
        owner = request.POST.get('owner', '')
        contact = request.POST.get('contact', '')
        level1 = request.POST.get('level1', '')
        level2 = request.POST.get('level2', '')
        level3 = request.POST.get('level3', '')
        status = request.POST.get('status', '')
        requestedby = request.POST.get('requestedby', '')
    

        if fleet:
            Items.objects.create(fleet=fleet,tail=tail,remark=remark, required_action=required_action, logged=logged, duedate=duedate,
                                 owner=owner, contact=contact, level1=level1, level2=level2, level3=level3, status=status, requestedby=requestedby, created_by=request.user)
            return redirect('/items/')
    return render(request, 'items/add.html')

@login_required
def edit_items(request, pk):
    items = Items.objects.filter(created_by=request.user).get(pk=pk)
    if request.method == "POST":
        fleet = request.POST.get('fleet', '')
        tail = request.POST.get('tail', '')
        remark = request.POST.get('remark', '')
        required_action = request.POST.get('required_action', '')
        logged = request.POST.get('logged', '')
        duedate = request.POST.get('duedate', '')
        owner = request.POST.get('owner', '')
        contact = request.POST.get('contact', '')
        level1 = request.POST.get('level1', '')
        level2 = request.POST.get('level2', '')
        level3 = request.POST.get('level3', '')
        status = request.POST.get('status', '')
        requestedby = request.POST.get('requestedby', '')

        if remark:
            items.fleet=fleet
            items.tail=tail
            items.remark=remark
            items.required_action=required_action
            items.logged=logged
            items.duedate=duedate
            items.owner=owner
            items.contact=contact
            items.level1=level1
            items.level2=level2
            items.level3=level3
            items.status=status
            items.requestedby=requestedby
            items.save()
            return redirect('/items/')
    return render(request, 'items/edit.html',{
        'items':items
    })

@login_required
def delete_items(request, pk):
    items = Items.objects.filter(created_by=request.user).get(pk=pk)
    items.delete()
    return redirect('/items/')

action/items/templates/items/add.html
{% extends 'core/base.html' %}
{% block content %}
<div class="bg-gray-300 border border-4 rounded-lg shadow relative m-10">

    <div class="flex items-start justify-between p-5 border-b rounded-t">
        <h3 class="text-xl font-semibold">
            Add Action Items
        </h3>
    </div>

    <div class="p-6 space-y-6">
        <form method="post" action=".">
            {% csrf_token %}
            <div class="grid grid-cols-6 gap-6">
                <div class="col-span-6 sm:col-span-3">
                    <label for="fleet" class="text-sm font-medium text-gray-900 block mb-2">Fleet</label>
                    <input type="text" name="fleet" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5" placeholder="B787”" required="">
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="tail" class="text-sm font-medium text-gray-900 block mb-2">Tail</label>
                    <input type="text" name="tail" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5" placeholder="ET-AUO">
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="owner" class="text-sm font-medium text-gray-900 block mb-2">Owner</label>
                    <input type="text" name="owner" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5" placeholder="Systems Engineering">
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="contact" class="text-sm font-medium text-gray-900 block mb-2">Contact</label>
                    <input type="email" name="contact" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5" placeholder="email">
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="duedate" class="text-sm font-medium text-gray-900 block mb-2">Due Date</label>
                    <input type="date" name="duedate" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5" placeholder="email">
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="logged" class="text-sm font-medium text-gray-900 block mb-2">Loged Date</label>
                    <input type="date" name="logged" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5" placeholder="email">
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="level1" class="text-sm font-medium text-gray-900 block mb-2">Level-1</label>
                    <input type="email" name="level1" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5" placeholder="email">
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="level2" class="text-sm font-medium text-gray-900 block mb-2">Level-2</label>
                    <input type="email" name="level2" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5" placeholder="email">
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="level3" class="text-sm font-medium text-gray-900 block mb-2">Level-3</label>
                    <input type="email" name="level3" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5" placeholder="email">
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="status" class="text-sm font-medium text-gray-900 block mb-2">Status</label>
                    <input type="text" name="status" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5" placeholder="Open/Closed">
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="requestedby" class="text-sm font-medium text-gray-900 block mb-2">Created By</label>
                    <input type="text" name="requestedby" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5" placeholder="">
                </div>
                <div class="col-span-full">
                    <label for="remark" class="text-sm font-medium text-gray-900 block mb-2">Remark</label>
                    <textarea name="remark" rows="6" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-4" placeholder="Details"></textarea>
                </div>
                <div class="col-span-full">
                    <label for="equired_action" class="text-sm font-medium text-gray-900 block mb-2">Required Action</label>
                    <textarea name="required_action" rows="6" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-4" placeholder="Details"></textarea>
                </div>
                <div class="p-6 border-t border-gray-200 rounded-b flex items-center justify-center ">
                    <button class="text-white bg-cyan-600 hover:bg-cyan-700 focus:ring-4 focus:ring-cyan-200 font-medium rounded-lg text-sm px-5 py-2.5 text-center" type="submit">Submit</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

action/items/templates/items/edit.html
{% extends 'core/base.html' %}
{% block content %}
<div class="bg-gray-300 border border-4 rounded-lg shadow relative m-10">

    <div class="flex items-start justify-between p-5 border-b rounded-t">
        <h3 class="text-xl font-semibold">
            Edit Action Items
        </h3>
    </div>

    <div class="p-6 space-y-6">
        <form method="post" action=".">
            {% csrf_token %}
            <div class="grid grid-cols-6 gap-6">
                <div class="col-span-6 sm:col-span-3">
                    <label for="fleet" class="text-sm font-medium text-gray-900 block mb-2">Fleet</label>
                    <input type="text" value="{{ items.fleet }}" name="fleet" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5" placeholder="B787”" required="">
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="tail" class="text-sm font-medium text-gray-900 block mb-2">Tail</label>
                    <input type="text" value="{{ items.tail }}" name="tail" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5" placeholder="ET-AUO">
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="owner" class="text-sm font-medium text-gray-900 block mb-2">Owner</label>
                    <input type="text" value="{{ items.owner }}" name="owner" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5" placeholder="Systems Engineering">
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="contact" class="text-sm font-medium text-gray-900 block mb-2">Contact</label>
                    <input type="email" value="{{ items.contact }}" name="contact" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5" placeholder="email">
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="duedate" class="text-sm font-medium text-gray-900 block mb-2">Due Date</label>
                    <input type="date" value="{{ items.duedate }}" name="duedate" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5" placeholder="email">
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="logged" class="text-sm font-medium text-gray-900 block mb-2">Loged Date</label>
                    <input type="date" value="{{ items.logged }}" name="logged" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5" placeholder="email">
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="level1" class="text-sm font-medium text-gray-900 block mb-2">Level-1</label>
                    <input type="email" value="{{ items.level1 }}" name="level1" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5" placeholder="email">
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="level2" class="text-sm font-medium text-gray-900 block mb-2">Level-2</label>
                    <input type="email" value="{{ items.level2 }}" name="level2" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5" placeholder="email">
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="level3" class="text-sm font-medium text-gray-900 block mb-2">Level-3</label>
                    <input type="email" value="{{ items.level3 }}" name="level3" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5" placeholder="email">
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="status" class="text-sm font-medium text-gray-900 block mb-2">Status</label>
                    <input type="text" value="{{ items.status }}" name="status" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5" placeholder="Open/Closed">
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="requestedby" class="text-sm font-medium text-gray-900 block mb-2">Created By</label>
                    <input type="text" value="{{ items.requestedby }}" name="requestedby" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5" placeholder="">
                </div>
                <div class="col-span-full">
                    <label for="remark" class="text-sm font-medium text-gray-900 block mb-2">Remark</label>
                    <textarea name="remark" rows="6" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-4" placeholder="Details">{{ items.remark }}"</textarea>
                </div>
                <div class="col-span-full">
                    <label for="equired_action" class="text-sm font-medium text-gray-900 block mb-2">Required Action</label>
                    <textarea name="required_action" rows="6" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-4" placeholder="Details">{{ items.required_action }}</textarea>
                </div>
                <div class="p-6 border-t border-gray-200 rounded-b flex items-center justify-center ">
                    <button class="text-white bg-cyan-600 hover:bg-cyan-700 focus:ring-4 focus:ring-cyan-200 font-medium rounded-lg text-sm px-5 py-2.5 text-center" type="submit">Save</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

action/items/templates/items/items.html
{% extends 'core/base.html' %}
{% block content %}
    <div class="px-2">
        <a href="{% url "items:add" %}">
            <button class="py-4 px-8 mt-2 hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700 rounded-lg text-white">New</button>
         </a>
    </div>
    <div class="mt-6 grid grid-cols-4 gap-4 px-4">
        {% for item in items %}
        <a href="{% url "items:view" item.id%}" class="block max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
                <div class="flex items-center justify-between">
                <p class="font-normal text-gray-700 dark:text-gray-400">{{ item.requestedby }}</p>
                <p class="flex items-center justify-end font-normal text-gray-700 dark:text-sky-500">{{ item.status }}</p>
                </div>
                <div class="flex items-center justify-between">
                    <p class="font-normal text-gray-700 dark:text-green-400">{{ item.logged }}</p>
                    <p class="flex items-center justify-end font-normal text-red-700 dark:text-red-400">{{ item.duedate }}</p>
                </div>
                <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">{{ item.tail }}</h5>
                <p class="font-normal text-gray-700 dark:text-gray-400">{{ item.remark | truncatechars:200}}</p>
                </a>
        </a>
        {% endfor %}
    </div>
{% endblock %}

action/items/templates/items/test.html
<a href="#" class="block max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">

    <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Noteworthy technology acquisitions 2021</h5>
    <p class="font-normal text-gray-700 dark:text-gray-400">Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.</p>
    </a>
    

action/items/templates/items/viewitem.html
{% extends 'core/base.html' %}

{% block content %}
<div class="bg-gray-400 mt-8 items-center justify-center px-4 sm:px-6 lg:px-8 ">
    <div class="w-full max-w-xxl space-y-2 ">
        <div class="bg-gray-300 shadow-md rounded-md p-4 border-2">

            <div class="space-x-4 flex items-center justify-end">
                <a href="{% url "items:edit" items.id %}">
                    <button type="submit"
                        class="flex justify-center rounded-md border border-transparent bg-green-500 py-2 px-4 text-md font-medium text-white shadow-sm hover:bg-opacity-75 focus:outline-none focus:ring-2 focus:ring-sky-400 focus:ring-offset-2">Edit
                    </button>
               </a>
               <a href="{% url "items:delete" items.id %}">
                    <button type="submit"
                        class="flex justify-center rounded-md border border-transparent bg-red-600 py-2 px-4 text-md font-medium text-white shadow-sm hover:bg-opacity-75 focus:outline-none focus:ring-2 focus:ring-sky-400 focus:ring-offset-2">Delete
                    </button>
                </a>
            </div>

            <div class="grid grid-cols-6 gap-6">
                <div class="col-span-6 sm:col-span-3">
                    <label for="fleet" class="text-sm font-medium text-gray-900 block mb-2">Fleet</label>
                    <text type="text" name="fleet" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5">{{ items.fleet }}<text/>
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="tail" class="text-sm font-medium text-gray-900 block mb-2">Tail</label>
                    <text type="text" name="tail" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5">{{ items.tail }}<text/>
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="owner" class="text-sm font-medium text-gray-900 block mb-2">Owner</label>
                    <text type="text" name="owner" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5">{{ items.owner }}<text/>
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="contact" class="text-sm font-medium text-gray-900 block mb-2">Contact</label>
                    <text type="email" name="contact" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5">{{ items.contact }}<text/>
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="duedate" class="text-sm font-medium text-gray-900 block mb-2">Due Date</label>
                    <text type="date" name="duedate" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5">{{ items.duedate }}<text/>
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="logged" class="text-sm font-medium text-gray-900 block mb-2">Loged Date</label>
                    <text type="date" name="logged" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5">{{ items.logged}}<text/>
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="level1" class="text-sm font-medium text-gray-900 block mb-2">Level-1</label>
                    <text type="email" name="level1" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5">{{ items.level1 }}<text/>
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="level2" class="text-sm font-medium text-gray-900 block mb-2">Level-2</label>
                    <text type="email" name="level2" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5">{{ items.level2 }}<text/>
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="level3" class="text-sm font-medium text-gray-900 block mb-2">Level-3</label>
                    <text type="email" name="level3" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5">{{ items.level3 }}<text/>
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="status" class="text-sm font-medium text-gray-900 block mb-2">Status</label>
                    <text type="text" name="status" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5">{{ items.status }}<text/>
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="requestedby" class="text-sm font-medium text-gray-900 block mb-2">Created By</label>
                    <text type="text" name="requestedby" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5">{{ items.status }}<text/>
                </div>
                <div class="col-span-full">
                    <label for="remark" class="text-sm font-medium text-gray-900 block mb-2">Remark</label>
                    <text name="remark" rows="6" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-4" placeholder="Details">{{ items.remark }}</textarea>
                </div>
                <div class="col-span-full">
                    <label for="equired_action" class="text-sm font-medium text-gray-900 block mb-2">Required Action</label>
                    <text name="required_action" rows="6" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-4" placeholder="Details">{{ items.required_action }}</textarea>
                </div>
            </div>

            <div class="flex items-center justify-center w-full max-w-xxl space-x-4 py-6 px-8 bg-gray-300">
                <div class="flex items-center justify-center space-x-4 py-6 px-8 bg-gray-100 shadow-md rounded-md p-4 border-2">
                    <label for="password" class="block text-xl font-medium text-gray-700">Send Email</label>
                    <button type="submit"
                        class="flex justify-center rounded-md border border-transparent bg-green-400 py-2 px-4 text-md font-medium text-white shadow-sm hover:bg-opacity-75 focus:outline-none focus:ring-2 focus:ring-sky-400 focus:ring-offset-2">Level-1
                    </button>
                    <button type="submit"
                        class="flex justify-center rounded-md border border-transparent bg-yellow-400 py-2 px-4 text-md font-medium text-white shadow-sm hover:bg-opacity-75 focus:outline-none focus:ring-2 focus:ring-sky-400 focus:ring-offset-2">Level-2
                    </button>
                    <button type="submit"
                        class="flex justify-center rounded-md border border-transparent bg-red-400 py-2 px-4 text-md font-medium text-white shadow-sm hover:bg-opacity-75 focus:outline-none focus:ring-2 focus:ring-sky-400 focus:ring-offset-2">Level-3
                    </button>
                </div>
            </div> 
        </div>
        
    </div>
</div>
{% endblock %}