action/account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
]

action/action/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('account.urls')),
    path('', include('items.urls')),
]

action/core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    #path('<uuid:pk>/', views.view_all, name='view_all'),
]

action/items/urls.py
from django.urls import path
from . import views

app_name = 'items'

urlpatterns = [
    path('items/', views.items, name='items'),
    path('add/', views.add_item, name='add'),
    path('<uuid:pk>/', views.view_items, name='view'),
    path('<uuid:pk>/edit/', views.edit_items, name='edit'),
    path('<uuid:pk>/delete/', views.delete_items, name='delete'),
] 

action/core/models.py
from django.db import models

# Create your models here.

action/core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from items.models import Items

@login_required
def index(request):
    items = Items.objects.values
    return render(request, 'core/index.html',{
        'items':items})

@login_required
def about(request):
    return render(request, 'core/about.html')
'''
@login_required
def view_all(request, pk):
    items = Items.objects.values

    return render(request, 'core/viewall.html',{
        'items':items
    })

'''

action/core/templates/core/about.html
{% extends 'core/base.html' %}
{% block content %}
    <header class="py-12 text-center bg-slate-200">
        <h1 class="text-3xl">About</h1>
    </header>
{% endblock %}

action/core/templates/core/base.html
<!doctype html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdn.tailwindcss.com"></script>
    </head>

    <body class="bg-gray-400" > 
        <nav class="py-6 px-8 flex items-center justify-between bg-gray-600">
            <h1 class="text-xl text-white"><a href="{% url "core:index" %}">Home</a></h1>

            <div class="space-x-4">
                <a href="{% url "core:about" %}" class="text-white">About</a>
                {% if request.user.is_authenticated %}
                    <a href="{% url "items:items" %}" class="py-4 px-8 text-white">My items</a>
                    <a href="{% url "account:logout" %}" class="py-4 px-8 text-white">Logout</a>
                    
                {% else %}
                    <a href="{% url "account:login" %}" class="py-4 px-8 text-white">Login</a>
                    <a href="{% url "account:signup" %}" class="py-4 px-8 text-white">Signup</a>
                {% endif %}
            </div>
        </nav>
        <main>
            {% block content %}
            {% endblock %}
        </main>

    </body>
</html>

action/core/templates/core/index.html
{% extends 'core/base.html' %}
{% block content %}
    <div class="flex items-center justify-between">
    <h1 class="text-3xl text-green px-2 py-2 text-gray-700">All Action Items</h1>
    <h1 class="text-3xl text-green px-2 py-2 text-gray-700">Filter</h1>
    </div>
    <div class="mt-2 grid grid-cols-4 gap-4 px-4">
        {% for item in items %}
        <a href="{% url "items:view" item.id%}" class="block max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
            <div class="flex items-center justify-between">
            <p class="font-normal text-gray-700 dark:text-gray-400">{{ item.requestedby }}</p>
            <p class="flex items-center justify-end font-normal text-gray-700 dark:text-sky-500">{{ item.status }}</p>
            </div>
            <div class="flex items-center justify-between">
                <p class="font-normal text-gray-700 dark:text-green-500">{{ item.logged }}</p>
                <p class="font-normal text-red-500 dark:text-red-500">{{ item.duedate }}</p>
            </div>
            <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">{{ item.tail }}</h5>
            <p class="font-normal text-gray-700 dark:text-gray-400">{{ item.remark | truncatechars:200}}</p>
        </a>
        
        {% endfor %}
    </div>
{% endblock %}

action/core/templates/core/viewall.html
{% extends 'core/base.html' %}

{% block content %}
<div class="bg-gray-100 mt-8 items-center justify-center px-4 sm:px-6 lg:px-8 ">
    <div class="w-full max-w-xxl space-y-2 ">
        <div class="bg-white shadow-md rounded-md p-4 border-2">


            <div class="grid grid-cols-6 gap-6">
                <div class="col-span-6 sm:col-span-3">
                    <label for="fleet" class="text-sm font-medium text-gray-900 block mb-2">Fleet</label>
                    <text type="text" name="fleet" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5">{{ items.fleet }}<text/>
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="tail" class="text-sm font-medium text-gray-900 block mb-2">Tail</label>
                    <text type="text" name="tail" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5">{{ items.tail }}<text/>
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="owner" class="text-sm font-medium text-gray-900 block mb-2">Owner</label>
                    <text type="text" name="owner" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5">{{ items.owner }}<text/>
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="contact" class="text-sm font-medium text-gray-900 block mb-2">Contact</label>
                    <text type="email" name="contact" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5">{{ items.contact }}<text/>
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="duedate" class="text-sm font-medium text-gray-900 block mb-2">Due Date</label>
                    <text type="date" name="duedate" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5">{{ items.duedate }}<text/>
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="logged" class="text-sm font-medium text-gray-900 block mb-2">Loged Date</label>
                    <text type="date" name="logged" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5">{{ items.logged}}<text/>
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="level1" class="text-sm font-medium text-gray-900 block mb-2">Level-1</label>
                    <text type="email" name="level1" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5">{{ items.level1 }}<text/>
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="level2" class="text-sm font-medium text-gray-900 block mb-2">Level-2</label>
                    <text type="email" name="level2" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5">{{ items.level2 }}<text/>
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="level3" class="text-sm font-medium text-gray-900 block mb-2">Level-3</label>
                    <text type="email" name="level3" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5">{{ items.level3 }}<text/>
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="status" class="text-sm font-medium text-gray-900 block mb-2">Status</label>
                    <text type="text" name="status" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5">{{ items.status }}<text/>
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <label for="requestedby" class="text-sm font-medium text-gray-900 block mb-2">Created By</label>
                    <text type="text" name="requestedby" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-2.5">{{ items.status }}<text/>
                </div>
                <div class="col-span-full">
                    <label for="remark" class="text-sm font-medium text-gray-900 block mb-2">Remark</label>
                    <text name="remark" rows="6" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-4" placeholder="Details">{{ items.remark }}</textarea>
                </div>
                <div class="col-span-full">
                    <label for="equired_action" class="text-sm font-medium text-gray-900 block mb-2">Required Action</label>
                    <text name="required_action" rows="6" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full p-4" placeholder="Details">{{ items.required_action }}</textarea>
                </div>
            </div>
        </div>
        
    </div>
</div>
{% endblock %}